import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import {
  Sidebar,
  SidebarContent,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarProvider,
  SidebarRail,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { HomeIcon } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="relative">
          <SidebarProvider>
            <Sidebar>
              <SidebarHeader>

                <SidebarMenu>
                  {[{ href: "/", label: "Home" }].map((link) => {
                    return (
                      <SidebarMenuItem key={link.href}>
                        <SidebarMenuButton>
                          <HomeIcon />
                          <span>{link.label}</span>
                        </SidebarMenuButton>
                      </SidebarMenuItem>
                    );
                  })}
                </SidebarMenu>
              </SidebarHeader>
              <SidebarContent className="pt-20">
              </SidebarContent>
              <SidebarRail />
            </Sidebar>
            {/* <SidebarTrigger /> */}
            {children}
          </SidebarProvider>
        </main>
      </body>
    </html>
  );
}
